name: Deploy to EC2

on:
  push:
    branches:
      - master  # or whatever branch you want to trigger on
    # paths:
    #   - .github/workflows/deploy.yml
    #   - terraform/main.tf 
      
jobs:
  deploy:
    runs-on: ubuntu-latest
    env:
      PRIVATE_KEY_BASE64: ${{ secrets.BASE64_PRIVATE_KEY_RSA }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_RSA_KEY: ${{secrets.PRIVATE_KEY_RSA}}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # - name: Install dependencies
      #   run: npm install 

      # Install dependencies, build your app if necessary here
      # - name: Setup Node.js
      #   uses: actions/setup-node@v2
      #   with:
      #       node-version: '21.6.1'
        
      # - name: Build React app
      #   run: npm run build
      - name: Print Environment Variables
        run: |
          echo "PRIVATE_KEY_BASE64: $PRIVATE_KEY_BASE64"
          echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
          echo "AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY"
          echo "AWS_RSA_KEY"

      - name: Terraform Init
        run: |
          cd terraform/
          terraform init -var="private_key_base64=${{ env.PRIVATE_KEY_BASE64 }}" -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"

      - name: Terraform Apply
        run: |
          cd terraform/
          terraform apply -auto-approve -var="private_key_base64=${{ env.PRIVATE_KEY_BASE64 }}" -var="aws_access_key_id=${{ env.AWS_ACCESS_KEY_ID }}" -var="aws_secret_access_key=${{ env.AWS_SECRET_ACCESS_KEY }}"